name:                fancfer
version:             0.1.0.0
github:              "CoderPuppy/fancfer"
license:             BSD3
author:              "CoderPuppy"
maintainer:          "coderpup@gmail.com"
copyright:           "2020 CoderPuppy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CoderPuppy/fancfer#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- unix
- containers
- text
- lens
- profunctors
- data-fix
- transformers
- mtl

default-extensions:
- DataKinds
- DefaultSignatures
- DeriveFunctor
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedLabels
- OverloadedStrings
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- UndecidableInstances
- ViewPatterns

ghc-options:
- -Wno-tabs

library:
  source-dirs: src

executables:
  fancfer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fancfer

tests:
  fancfer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fancfer
